package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"golang/graph/model"
)

// CreatUser is the resolver for the CreatUser field.
func (r *mutationResolver) CreatUser(ctx context.Context, input model.NewUser) (*model.User, error) {
	return r.Svc.UserSignUp(input)
}

// CreatCompany is the resolver for the CreatCompany field.
func (r *mutationResolver) CreatCompany(ctx context.Context, input model.NewCompany) (*model.Company, error) {
	return r.Svc.CreatCompany(input)
}

// ViewCompanyByID is the resolver for the ViewCompanyById field.
func (r *queryResolver) ViewCompanyByID(ctx context.Context, cid string) (*model.Company, error) {
	return r.Svc.ViewCompanyById(cid)
}

// ViewAllCompany is the resolver for the ViewAllCompany field.
func (r *queryResolver) ViewAllCompany(ctx context.Context) ([]*model.Company, error) {
	return r.Svc.ViewAllcompany()
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
