// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Company struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Location string `json:"location"`
	Salary   string `json:"salary"`
}

type NewCompany struct {
	Name     string `json:"name"`
	Location string `json:"location"`
	Salary   string `json:"salary"`
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
	UpdatedAt string `json:"updated_at"`
}
